version: "3.4"
services:
  web:
    build: ./web
    command: yarn start
    environment:
      - PORT=8000
    volumes:
      - ./web:/app
      - node-modules:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - api
  api: &api
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - vendor:/app/vendor/bundle
    ports:
      - "3000:3000"
    env_file:
      - ./env/common.env
      - ./env/api.env
    depends_on:
      - db
      - redis
  worker:
    <<: *api
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/redis
    command: redis-server --appendonly yes
volumes:
  node-modules:
  vendor:
  postgres-data:
  redis:
