default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: api_development
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: postgres
  password:
test:
  <<: *default
  database: api_test
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: postgres
  password:
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
